name: super_easy_permissions
description: A flutter plugin for handling permissions on Android and iOS.
version: 0.0.1
authors: Rituraj Shakti
homepage: https://github.com/riturajshakti

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.riturajshakti.super_easy_permissions
        pluginClass: SuperEasyPermissionsPlugin
      ios:
        pluginClass: SuperEasyPermissionsPlugin
